case $1 in
    mysql)
        (cd / && ./runMySQL.sh)
        mysql -u root --password=root -e "CREATE DATABASE supertokens;"
        mysql -u root --password=root -e "CREATE DATABASE st0;"
        mysql -u root --password=root -e "CREATE DATABASE st1;"
        mysql -u root --password=root -e "CREATE DATABASE st2;"
        mysql -u root --password=root -e "CREATE DATABASE st3;"
        mysql -u root --password=root -e "CREATE DATABASE st4;"
        mysql -u root --password=root -e "CREATE DATABASE st5;"
        mysql -u root --password=root -e "CREATE DATABASE st6;"
        mysql -u root --password=root -e "CREATE DATABASE st7;"
        mysql -u root --password=root -e "CREATE DATABASE st8;"
        mysql -u root --password=root -e "CREATE DATABASE st9;"
        mysql -u root --password=root -e "CREATE DATABASE st10;"
        mysql -u root --password=root -e "CREATE DATABASE st11;"
        mysql -u root --password=root -e "CREATE DATABASE st12;"
        mysql -u root --password=root -e "CREATE DATABASE st13;"
        mysql -u root --password=root -e "CREATE DATABASE st14;"
        mysql -u root --password=root -e "CREATE DATABASE st15;"
        mysql -u root --password=root -e "CREATE DATABASE st16;"
        mysql -u root --password=root -e "CREATE DATABASE st17;"
        mysql -u root --password=root -e "CREATE DATABASE st18;"
        mysql -u root --password=root -e "CREATE DATABASE st19;"
        mysql -u root --password=root -e "CREATE DATABASE st20;"
        mysql -u root --password=root -e "CREATE DATABASE st21;"
        mysql -u root --password=root -e "CREATE DATABASE st22;"
        mysql -u root --password=root -e "CREATE DATABASE st23;"
        mysql -u root --password=root -e "CREATE DATABASE st24;"
        mysql -u root --password=root -e "CREATE DATABASE st25;"
        mysql -u root --password=root -e "CREATE DATABASE st26;"
        mysql -u root --password=root -e "CREATE DATABASE st27;"
        mysql -u root --password=root -e "CREATE DATABASE st28;"
        mysql -u root --password=root -e "CREATE DATABASE st29;"
        mysql -u root --password=root -e "CREATE DATABASE st30;"
        mysql -u root --password=root -e "CREATE DATABASE st31;"
        mysql -u root --password=root -e "CREATE DATABASE st32;"
        mysql -u root --password=root -e "CREATE DATABASE st33;"
        mysql -u root --password=root -e "CREATE DATABASE st34;"
        mysql -u root --password=root -e "CREATE DATABASE st35;"
        mysql -u root --password=root -e "CREATE DATABASE st36;"
        mysql -u root --password=root -e "CREATE DATABASE st37;"
        mysql -u root --password=root -e "CREATE DATABASE st38;"
        mysql -u root --password=root -e "CREATE DATABASE st39;"
        mysql -u root --password=root -e "CREATE DATABASE st40;"
        mysql -u root --password=root -e "CREATE DATABASE st41;"
        mysql -u root --password=root -e "CREATE DATABASE st42;"
        mysql -u root --password=root -e "CREATE DATABASE st43;"
        mysql -u root --password=root -e "CREATE DATABASE st44;"
        mysql -u root --password=root -e "CREATE DATABASE st45;"
        mysql -u root --password=root -e "CREATE DATABASE st46;"
        mysql -u root --password=root -e "CREATE DATABASE st47;"
        mysql -u root --password=root -e "CREATE DATABASE st48;"
        mysql -u root --password=root -e "CREATE DATABASE st49;"
        mysql -u root --password=root -e "CREATE DATABASE st50;"
        ;;
    postgresql)
        /etc/init.d/postgresql start
        sudo -u postgres psql --command "CREATE USER root WITH SUPERUSER PASSWORD 'root';"
        createdb
        psql -c "create database supertokens;"
        psql -c "create database st0;"
        psql -c "create database st1;"
        psql -c "create database st2;"
        psql -c "create database st3;"
        psql -c "create database st4;"
        psql -c "create database st5;"
        psql -c "create database st6;"
        psql -c "create database st7;"
        psql -c "create database st8;"
        psql -c "create database st9;"
        psql -c "create database st10;"
        psql -c "create database st11;"
        psql -c "create database st12;"
        psql -c "create database st13;"
        psql -c "create database st14;"
        psql -c "create database st15;"
        psql -c "create database st16;"
        psql -c "create database st17;"
        psql -c "create database st18;"
        psql -c "create database st19;"
        psql -c "create database st20;"
        psql -c "create database st21;"
        psql -c "create database st22;"
        psql -c "create database st23;"
        psql -c "create database st24;"
        psql -c "create database st25;"
        psql -c "create database st26;"
        psql -c "create database st27;"
        psql -c "create database st28;"
        psql -c "create database st29;"
        psql -c "create database st30;"
        psql -c "create database st31;"
        psql -c "create database st32;"
        psql -c "create database st33;"
        psql -c "create database st34;"
        psql -c "create database st35;"
        psql -c "create database st36;"
        psql -c "create database st37;"
        psql -c "create database st38;"
        psql -c "create database st39;"
        psql -c "create database st40;"
        psql -c "create database st41;"
        psql -c "create database st42;"
        psql -c "create database st43;"
        psql -c "create database st44;"
        psql -c "create database st45;"
        psql -c "create database st46;"
        psql -c "create database st47;"
        psql -c "create database st48;"
        psql -c "create database st49;"
        psql -c "create database st50;"
esac