case $1 in
    mysql)
        (cd / && ./runMySQL.sh)
        mysql -u root --password=root -e "CREATE DATABASE supertokens;"
        mysql -u root --password=root -e "CREATE DATABASE st0;"
        mysql -u root --password=root -e "CREATE DATABASE st1;"
        mysql -u root --password=root -e "CREATE DATABASE st2;"
        mysql -u root --password=root -e "CREATE DATABASE st3;"
        mysql -u root --password=root -e "CREATE DATABASE st4;"
        mysql -u root --password=root -e "CREATE DATABASE st5;"
        mysql -u root --password=root -e "CREATE DATABASE st6;"
        mysql -u root --password=root -e "CREATE DATABASE st7;"
        mysql -u root --password=root -e "CREATE DATABASE st8;"
        mysql -u root --password=root -e "CREATE DATABASE st9;"
        mysql -u root --password=root -e "CREATE DATABASE st10;"
        mysql -u root --password=root -e "CREATE DATABASE st11;"
        mysql -u root --password=root -e "CREATE DATABASE st12;"
        mysql -u root --password=root -e "CREATE DATABASE st13;"
        mysql -u root --password=root -e "CREATE DATABASE st14;"
        mysql -u root --password=root -e "CREATE DATABASE st15;"
        mysql -u root --password=root -e "CREATE DATABASE st16;"
        mysql -u root --password=root -e "CREATE DATABASE st17;"
        mysql -u root --password=root -e "CREATE DATABASE st18;"
        mysql -u root --password=root -e "CREATE DATABASE st19;"
        mysql -u root --password=root -e "CREATE DATABASE st20;"
        mysql -u root --password=root -e "CREATE DATABASE st21;"
        mysql -u root --password=root -e "CREATE DATABASE st22;"
        mysql -u root --password=root -e "CREATE DATABASE st23;"
        mysql -u root --password=root -e "CREATE DATABASE st24;"
        mysql -u root --password=root -e "CREATE DATABASE st25;"
        mysql -u root --password=root -e "CREATE DATABASE st26;"
        mysql -u root --password=root -e "CREATE DATABASE st27;"
        mysql -u root --password=root -e "CREATE DATABASE st28;"
        mysql -u root --password=root -e "CREATE DATABASE st29;"
        mysql -u root --password=root -e "CREATE DATABASE st30;"
        mysql -u root --password=root -e "CREATE DATABASE st31;"
        mysql -u root --password=root -e "CREATE DATABASE st32;"
        mysql -u root --password=root -e "CREATE DATABASE st33;"
        mysql -u root --password=root -e "CREATE DATABASE st34;"
        mysql -u root --password=root -e "CREATE DATABASE st35;"
        mysql -u root --password=root -e "CREATE DATABASE st36;"
        mysql -u root --password=root -e "CREATE DATABASE st37;"
        mysql -u root --password=root -e "CREATE DATABASE st38;"
        mysql -u root --password=root -e "CREATE DATABASE st39;"
        mysql -u root --password=root -e "CREATE DATABASE st40;"
        mysql -u root --password=root -e "CREATE DATABASE st41;"
        mysql -u root --password=root -e "CREATE DATABASE st42;"
        mysql -u root --password=root -e "CREATE DATABASE st43;"
        mysql -u root --password=root -e "CREATE DATABASE st44;"
        mysql -u root --password=root -e "CREATE DATABASE st45;"
        mysql -u root --password=root -e "CREATE DATABASE st46;"
        mysql -u root --password=root -e "CREATE DATABASE st47;"
        mysql -u root --password=root -e "CREATE DATABASE st48;"
        mysql -u root --password=root -e "CREATE DATABASE st49;"
        mysql -u root --password=root -e "CREATE DATABASE st50;"
        ;;
esac