name: Release – Publish Docker images

on:
  workflow_call:
    inputs:
      core-version:
        type: string
        required: true
      is-canary:
        type: boolean
        required: true
      is-latest-release:
        type: boolean
        required: true
      is-latest-for-major:
        type: boolean
        required: true
      push-to-ecr:
        type: boolean
        required: true
      dev-tag:
        type: string
        required: true

jobs:
  release-docker:
    name: Release Docker image
    environment: publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push release images to Docker Hub
        run: |
          bash .github/helpers/push-release-docker-tags.sh \
            "supertokens/supertokens-dev-postgresql:${{ inputs.dev-tag }}" \
            "supertokens/supertokens-postgresql" \
            "${{ inputs.core-version }}" \
            "${{ inputs.is-canary }}" \
            "${{ inputs.is-latest-for-major }}" \
            "${{ inputs.is-latest-release }}"

      - name: Configure AWS credentials
        if: inputs.push-to-ecr
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        if: inputs.push-to-ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7

      - name: Push release images to ECR
        if: inputs.push-to-ecr
        run: |
          bash .github/helpers/push-release-docker-tags.sh \
            "supertokens/supertokens-dev-postgresql:${{ inputs.dev-tag }}" \
            "${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}" \
            "${{ inputs.core-version }}" \
            "${{ inputs.is-canary }}" \
            "${{ inputs.is-latest-for-major }}" \
            "${{ inputs.is-latest-release }}"
