name: Release

on:
  workflow_dispatch:
    inputs:
      core-version:
        description: 'Core version (e.g. 11.4.0)'
        required: true
        type: string
      plugin-interface-version:
        description: 'Plugin interface version (e.g. 8.4.0)'
        required: true
        type: string
      postgresql-plugin-version:
        description: 'PostgreSQL plugin version (e.g. 9.4.0)'
        required: true
        type: string
      release-plugin-interface:
        description: 'Release a new plugin-interface version'
        required: true
        type: boolean
        default: true
      release-postgresql-plugin:
        description: 'Release a new postgresql-plugin version'
        required: true
        type: boolean
        default: true
      is-latest-release:
        description: 'Is this the latest release? (tags the Docker image as "latest")'
        required: true
        type: boolean
        default: true
      is-latest-for-major:
        description: 'Is this the latest release for its major version? (tags the Docker image with the major version, e.g. "9")'
        required: true
        type: boolean
        default: true
      run-stress-tests:
        description: 'Run stress tests'
        required: true
        type: boolean
        default: true
      is-canary:
        description: 'Is this a canary release?'
        required: true
        type: boolean
        default: false
      push-to-ecr:
        description: 'Push Docker images to Amazon ECR'
        required: true
        type: boolean
        default: true

jobs:
  dependency-branches:
    uses: ./.github/workflows/_release-resolve-deps.yml
    with:
      core-version: ${{ inputs.core-version }}
      plugin-interface-version: ${{ inputs.plugin-interface-version }}
      postgresql-plugin-version: ${{ inputs.postgresql-plugin-version }}
    secrets: inherit

  register-versions:
    needs: dependency-branches
    uses: ./.github/workflows/_release-register-versions.yml
    with:
      core-version: ${{ inputs.core-version }}
      core-sha: ${{ needs.dependency-branches.outputs.core-sha }}
      postgresql-plugin-version: ${{ inputs.postgresql-plugin-version }}
      postgresql-sha: ${{ needs.dependency-branches.outputs.postgresql-sha }}
      release-postgresql-plugin: ${{ inputs.release-postgresql-plugin }}
      is-canary: ${{ inputs.is-canary }}
    secrets: inherit

  test:
    needs: [ dependency-branches, register-versions ]
    uses: ./.github/workflows/_release-run-tests.yml
    with:
      core-sha: ${{ needs.dependency-branches.outputs.core-sha }}
      plugin-interface-sha: ${{ needs.dependency-branches.outputs.plugin-interface-sha }}
      postgresql-sha: ${{ needs.dependency-branches.outputs.postgresql-sha }}
    secrets: inherit

  mark-as-passed:
    needs: [ register-versions, test ]
    if: ${{ !cancelled() && !failure() }}
    uses: ./.github/workflows/_release-mark-passed.yml
    with:
      core-version: ${{ inputs.core-version }}
      postgresql-plugin-version: ${{ inputs.postgresql-plugin-version }}
      release-postgresql-plugin: ${{ inputs.release-postgresql-plugin }}
      is-canary: ${{ inputs.is-canary }}
    secrets: inherit

  build-docker:
    needs: dependency-branches
    uses: ./.github/workflows/_release-build-docker.yml
    with:
      core-version: ${{ inputs.core-version }}
      is-canary: ${{ inputs.is-canary }}
      core-sha: ${{ needs.dependency-branches.outputs.core-sha }}
      plugin-interface-sha: ${{ needs.dependency-branches.outputs.plugin-interface-sha }}
      postgresql-sha: ${{ needs.dependency-branches.outputs.postgresql-sha }}
    secrets: inherit

  stress-tests:
    if: inputs.run-stress-tests
    needs: [ build-docker ]
    uses: ./.github/workflows/stress-tests.yml
    with:
      tag: ${{ needs.build-docker.outputs.dev-tag }}

  release-docker:
    needs: [ build-docker, stress-tests, mark-as-passed ]
    if: ${{ !cancelled() && !failure() }}
    uses: ./.github/workflows/_release-publish-docker.yml
    with:
      core-version: ${{ inputs.core-version }}
      is-canary: ${{ inputs.is-canary }}
      is-latest-release: ${{ inputs.is-latest-release }}
      is-latest-for-major: ${{ inputs.is-latest-for-major }}
      push-to-ecr: ${{ inputs.push-to-ecr }}
      dev-tag: ${{ needs.build-docker.outputs.dev-tag }}
    secrets: inherit

  add-release-tags:
    needs: [dependency-branches, release-docker]
    if: ${{ !cancelled() && !failure() }}
    uses: ./.github/workflows/_release-add-tags.yml
    with:
      core-version: ${{ inputs.core-version }}
      plugin-interface-version: ${{ inputs.plugin-interface-version }}
      postgresql-plugin-version: ${{ inputs.postgresql-plugin-version }}
      core-sha: ${{ needs.dependency-branches.outputs.core-sha }}
      plugin-interface-sha: ${{ needs.dependency-branches.outputs.plugin-interface-sha }}
      postgresql-sha: ${{ needs.dependency-branches.outputs.postgresql-sha }}
      release-plugin-interface: ${{ inputs.release-plugin-interface }}
      release-postgresql-plugin: ${{ inputs.release-postgresql-plugin }}
      is-canary: ${{ inputs.is-canary }}
      is-latest-release: ${{ inputs.is-latest-release }}
    secrets: inherit

  build-jars:
    needs: [add-release-tags]
    if: ${{ !cancelled() && !failure() && !inputs.is-canary }}
    uses: ./.github/workflows/generate-jars.yml
    with:
      core-version: ${{ inputs.core-version }}
      plugin-interface-version: ${{ inputs.plugin-interface-version }}
      postgresql-plugin-version: ${{ inputs.postgresql-plugin-version }}
      commit-to-github: true
    secrets: inherit
