name: "Run tests"
on:
  workflow_dispatch:
    inputs:
      pluginRepoOwnerName:
        description: 'supertokens-plugin-interface repo owner name'
        default: supertokens
        required: true
      pluginInterfaceBranch:
        description: 'supertokens-plugin-interface repos branch name'
        default: master
        required: true

jobs:
  test_job:
    name: Run tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: rishabhpoddar/supertokens_core_testing
    steps:
      - uses: actions/checkout@v2
      - name: Cloning supertokens-root
        run: cd ../ && git clone https://github.com/supertokens/supertokens-root.git
      - name: Update Java 1
        run: update-alternatives --install "/usr/bin/java" "java" "/usr/java/jdk-15.0.1/bin/java" 2
      - name: Update Java 2
        run: update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/jdk-15.0.1/bin/javac" 2
      - name: Modifying modules.txt in supertokens-root
        run: cd ../supertokens-root && echo "core,master\nplugin-interface,${{ github.event.inputs.pluginInterfaceBranch }},${{ github.event.inputs.pluginRepoOwnerName }}" > modules.txt
      - name: Contents of modules.txt
        run: cat ../supertokens-root/modules.txt
      - name: Running loadModules in supertokens-root
        run: cd ../supertokens-root && ./loadModules
      - name: Copying current supertokens-core branch into supertokens-root
        run: cd ../supertokens-root && rm -rf ./supertokens-core && cp -r ../supertokens-core ./
      - name: Building and running tests
        run: cd ../supertokens-root && ./startTestingEnv