name: "Run tests"
on:
  workflow_dispatch:
    inputs:
      pluginInterfaceBranch:
        description: 'Plugin interface branch name'     
        required: true

jobs:
  test_job:
    runs-on: rishabhpoddar/supertokens_core_testing
    steps:
      - uses: actions/checkout@v2
